### ISSUE TITLE
데모 링크 버튼 404 오류

### ISSUE THREAD

**Issue by woochul2** [next-step/js-todo-list-step1#178]
데모 링크에서 '전체보기' 버튼을 누르면 404 에러가 뜨네요.
레벨2 데모링크 사이트 버튼도 마찬가지인 것 같습니다

**Comment by EungyuCho** [comment]
`li`요소의 `a`태그 안에 `href`속성이 /#로 되어있어서 깃허브 io의 루트로 바로 넘어가서 이런 현상이 생기는군요 😢 

레벨 2의 경우도 동일 현상이네요
